apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fedemeter-influxdb
  namespace: {{.NameSpace}}
  labels:
    app: alameda
    component: fedemeter-influxdb
spec:
  serviceName: fedemeter-influxdb
  selector:
    matchLabels:
      app : fedemeter-influxdb
  template:
    metadata:
      labels:
        app: fedemeter-influxdb
    spec:
      #nodeSelector:
      #  kubernetes.io/hostname: "netrg6akfi-worker-1"
      containers:
      - name: fedemeter-influxdb
        image: {{.Image.FedemeterInfluxDB}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8086
        tty: true
        #resources:
        #  limits:
        #    cpu: "1000m"
#    memory: "1000Mi"